import Head from 'next/head'
import React, { FC } from 'react'
import Navbar from '../Navbar'

import styles from "./MainLayout.module.css";

interface Props {
  children: React.ReactNode
}

const MainLayout : FC<Props> = ( { children }) => {
  return (
    <div className={ styles.container }>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      
      <main className={ styles.main }>
        { children }
      </main>
    </div>
  )
}


export default MainLayout;